kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres/data"