apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: redis
    spec:
      containers:
      - image: redis:3.2
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-storage
      restartPolicy: Always
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-volume-claim
status: {}
