apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: superset
  name: superset
spec:
  ports:
  - name: "8088"
    protocol: TCP
    port: 8088
    targetPort: 8088
  selector:
    service: superset
status:
  loadBalancer: {}
