apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: superset
  name: superset
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: superset
    spec:
      containers:
      - args:
        - tail
        - -f
        - /dev/null
        env:
        - name: POSTGRES_DB
          value: superset
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PASSWORD
          value: superset
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: superset
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: SUPERSET_ENV
          value: local
        image: artifacts.ggn.in.guavus.com:4245/guavus-superset:1.0.4
        name: superset
        ports:
        - containerPort: 8088
          hostPort: 8088
        resources: {}
        volumeMounts:
        - mountPath: /home/work/incubator-superset/superset/assets/node_modules
          name: superset-node-modules-storage
      restartPolicy: Always
      volumes:
      - name: superset-node-modules-storage
        persistentVolumeClaim:
          claimName: superset-node-modules-volume-claim
status: {}
