kind: PersistentVolume
apiVersion: v1
metadata:
  name: superset-node-modules-volume
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/superset-node_modules/data"