coverage:
  status:
    project:
      default:
        # Commits pushed to master should not make the overall
        # project coverage decrease by more than 1%:
        target: auto
        threshold: 1%
    patch:
      default:
        # Due to the current low code coverage, setting a
        # specific target for diffs
        target: 80%

ignore:
- "superset/assets/src/visualizations/"
