cache:
  - pip
matrix:
  include:
    - language: python
      python: 2.7
      env: TOXENV=flake8
      services:
        - mysql
        - redis-server
    - language: python
      python: 3.6
      env: TOXENV=flake8
      services:
        - mysql
        - redis-server
    - language: python
      python: 2.7
      env: TOXENV=py27-mysql
      services:
        - mysql
        - redis-server
    - language: python
      python: 2.7
      env: TOXENV=py27-sqlite
      services:
        - redis-server
      before_script: skip
    - language: node_js
      node_js: 6
      before_script: skip
      before_install:
        - cd superset/assets
      install:
        - yarn install
      script:
        - npm run lint
        - npm run test
        - npm run build
before_script:
  - mysql -u root -e "DROP DATABASE IF EXISTS superset; CREATE DATABASE superset DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
  - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"
  - mysql -u root -e "GRANT ALL ON superset.* TO 'mysqluser'@'localhost';"
  - psql -U postgres -c "CREATE DATABASE superset;"
  - psql -U postgres -c "CREATE USER postgresuser WITH PASSWORD 'pguserpassword';"
install:
  - pip install --upgrade pip
  - pip install codecov tox
script:
  - tox
after_success:
  - codecov

# language: python
# python:
#   - 2.7
#   - 3.6
# cache:
#   - pip
# services:
#   - mysql
#   - postgres
#   - redis-server
# matrix:
#   include:
#     - python: 2.7
#       env: TOXENV=flake8
#     - python: 2.7
#       env: TOXENV=py27-mysql
#     - python: 2.7
#       env: TOXENV=py27-sqlite
#     - python: 2.7
#       env: TOXENV=pylint
#     - python: 3.6
#       env: TOXENV=flake8
#     - python: 3.6
#       env: TOXENV=javascript
#     - python: 3.6
#       env: TOXENV=py36-postgres
#     - python: 3.6
#       env: TOXENV=py36-sqlite
#     - python: 3.6
#       env: TOXENV=pylint
#     - python: 3.6
#       env: TOXENV=cypress
#   exclude:
#     - python: 2.7
#     - python: 3.6
# before_script:
#   - mysql -u root -e "DROP DATABASE IF EXISTS superset; CREATE DATABASE superset DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
#   - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"
#   - mysql -u root -e "GRANT ALL ON superset.* TO 'mysqluser'@'localhost';"
#   - psql -U postgres -c "CREATE DATABASE superset;"
#   - psql -U postgres -c "CREATE USER postgresuser WITH PASSWORD 'pguserpassword';"
