language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
cache:
  directories:
    - $HOME/.wheelhouse/
env:
  global:
    - TRAVIS_CACHE=$HOME/.travis_cache/
  matrix:
    - TOX_ENV=py27-mysql
    - TOX_ENV=py27-sqlite
    - TOX_ENV=py27-postgres
    - TOX_ENV=py34-mysql
    - TOX_ENV=javascript
before_install:
  - npm install -g npm@'>=2.7.1'
before_script:
  - mysql -e 'drop database if exists airflow; create database airflow' -u root
  - psql -c 'create database airflow;' -U postgres
  - export PATH=${PATH}:/tmp/hive/bin
install:
  - pip install --upgrade pip
  - pip install tox tox-travis
script: tox -e $TOX_ENV
