#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
jobs:
  include:
    - language: python
      python: 3.6
      env:
        - TOXENV=fossa
    - language: python
      python: 3.6
      env:
        - TOXENV=license-check
        - TRAVIS_CACHE=$HOME/.travis_cache/
      addons:
        apt:
          packages:
            - openjdk-8-jdk
    - language: python
      python: 3.6
      env: TOXENV=cypress-dashboard
      services:
        - redis
      before_install:
        - nvm install 10.14.2
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF cypress,dashboard
    - language: python
      python: 3.6
      env: TOXENV=cypress-explore
      services:
        - redis
      before_install:
        - nvm install 10.14.2
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF cypress,explore
    - language: python
      python: 3.6
      env: TOXENV=cypress-sqllab
      services:
        - redis
      before_install:
        - nvm install 10.14.2
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF cypress,sqllab
    - language: python
      python: 3.6
      env: TOXENV=py36-mysql
      services:
        - mysql
        - redis
      before_script:
        - mysql -u root -e "DROP DATABASE IF EXISTS superset; CREATE DATABASE superset DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
        - mysql -u root -e "DROP DATABASE IF EXISTS sqllab_test_db; CREATE DATABASE sqllab_test_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
        - mysql -u root -e "DROP DATABASE IF EXISTS admin_database; CREATE DATABASE admin_database DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci"
        - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"
        - mysql -u root -e "GRANT ALL ON *.* TO 'mysqluser'@'localhost';"
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF unittest,python,mysql
    - language: python
      env: TOXENV=javascript
      before_install:
        - nvm install 10.14.2
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF unittest,javascript
    - language: python
      python: 3.6
      env: TOXENV=black
    - language: python
      python: 3.6
      env: TOXENV=isort
    - language: python
      python: 3.6
      env: TOXENV=mypy
    - language: python
      python: 3.6
      env: TOXENV=py36-sqlite
      services:
        - redis
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF unittest,python,sqllite
    - language: python
      python: 3.6
      env: TOXENV=py36-postgres
      services:
        - postgresql
        - redis
      before_script:
        - psql -U postgres -c "DROP DATABASE IF EXISTS superset;"
        - psql -U postgres -c "CREATE DATABASE superset;"
        - psql -U postgres superset -c "DROP SCHEMA IF EXISTS sqllab_test_db;"
        - psql -U postgres superset -c "CREATE SCHEMA sqllab_test_db;"
        - psql -U postgres superset -c "DROP SCHEMA IF EXISTS admin_database;"
        - psql -U postgres superset -c "CREATE SCHEMA admin_database;"
        - psql -U postgres -c "CREATE USER postgresuser WITH PASSWORD 'pguserpassword';"
        - psql -U postgres superset -c "GRANT ALL PRIVILEGES ON SCHEMA sqllab_test_db to postgresuser";
        - psql -U postgres superset -c "GRANT ALL PRIVILEGES ON SCHEMA admin_database to postgresuser";
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF unittest,python,postgres
    - language: python
      python: 3.6
      env: TOXENV=pylint
    - language: python
      python: 3.6
      env: TOXENV=docs

script:
  - tox
cache:
  pip: true
  directories:
    - ~/.npm
    - ~/.cache
    - ~/.travis_cache/
    - superset-frontend/.terser-plugin-cache/
addons:
  apt:
    packages:
      - libgconf-2-4
install:
  - pip install --upgrade pip
  - pip install tox
