[tool.apache-superset]
name = "apache-superset"
version = "0.1.0"
description = "A modern, enterprise-ready business intelligence web application"

license = "MIT"

authors = [
    "Apache Software Foundation"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/apache/incubator-superset"
homepage = "https://superset.apache.org/"

keywords = ["superset"]

[tool.apache-superset.dependencies]
python = "~3.6"  # Compatible python versions must be declared here
toml = "^0.9"
# Dependencies with extras
bleach = { version = "^3.0.2" }
celery = { version = "^4.3.0" }
click = { version = "^6.0" }
colorama = { version = "^0" }
contextlib2 = { version = "^0" }
croniter = { version = "^0.3.28" }
cryptography = { version = "^2.4.2" }
flask = { version = "^1" }
flask-appbuilder = { version = "^2.1.9" }
flask-caching = { version = "^1.4" }
flask-compress = { version = "^1.4" }
flask-talisman = { version = "^0" }
flask-migrate = { version = "^2.1.1" }
flask-wtf = { version = "^0" }
geopy = { version = "^1" }
gunicorn = { version = "~19.8" }
humanize = { version = "^0" }
idna = { version = "^2" }
isodate = { version = "^0" }
markdown = { version = "^3.0" }
pandas = { version = "~0.24.2"}
parsedatetime = { version = "^2" }
pathlib2 = { version = "^2" }
polyline = { version = "^1" }
python-dateutil = { version = "^2" }
python-dotenv = { version = "^0" }
python-geohash = { version = "^0" }
pyyaml = { version = "^5.1" }
retry = { version = "^0.9.2" }
selenium = { version = "^3.141" }
simplejson = { version = "^3.15" }
sqlalchemy = { version = "^1.3.5" }
sqlalchemy-utils = { version = "^0.33.2" }
sqlparse = { version = "^0.3" }
wtforms-json = { version = "^0" }

# Optional dependencies (extras)
pendulum = { version = "^1.4", optional = true }

[tool.apache-superset.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.4"

[tool.apache-superset.scripts]
my-script = 'my_package:main'
