apiVersion: v1
kind: Secret
metadata:
  name: {{ template "superset.fullname" . }}-config
  labels:
    app: {{ template "superset.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data: 
  superset_config.py: {{ include "superset-connections.script" . | b64enc }}