apiVersion: v1
kind: Secret
metadata:
  name: {{ template "superset.fullname" . }}-secret
  labels:
    app: {{ template "superset.fullname" . }}
    chart: {{ template "superset.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
    redis_host: {{ .Values.supersetNode.connections.redis_host | b64enc | quote }}
    redis_port: {{ .Values.supersetNode.connections.redis_port | b64enc | quote }}
    db_host: {{ .Values.supersetNode.connections.db_host | b64enc | quote }}
    db_port: {{ .Values.supersetNode.connections.db_port | b64enc | quote }}
    db_user: {{ .Values.supersetNode.connections.db_user | b64enc | quote }}
    db_pass: {{ .Values.supersetNode.connections.db_pass | b64enc | quote }}
    db_name: {{ .Values.supersetNode.connections.db_name | b64enc | quote }}