---

# create sql dirs
- name: Create base directories
  file:
    path: "{{superset_host_sql_dir}}/{{item}}/createdb"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: 0755
  with_items: ["postgres"]


# copy/templatize all SQL template files for all DB types

- name: check if db template dir exists
  local_action: stat path="{{role_path}}/templates/{{item}}/"
  with_items: [ "postgres"]
  register: sql_template_dir

- name: Listing template files
  local_action: find path="{{item.stat.path}}/createdb"
  register: sql_template_files_createdb
  with_items: "{{sql_template_dir.results}}"

- name: Copy template SQL files to {{ superset_host_sql_dir }}
  template:
      src: "{{item.1.path}}"
      dest: "{{superset_host_sql_dir}}/{{ item.0.item.item }}/createdb/{{ (item.1.path|basename) | splitext | first }}"
      owner: root
      group: root
      mode: 0644
  with_subelements:
     - "{{ sql_template_files_createdb.results }}"
     - "files"