name: Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag to build'
        required: true
        default: '0.38.0'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - shell: bash
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GITHUB_REF: ${{ github.event.inputs.tag }}
        run: |
          cat GITHUB_REF
          git rev-parse HEAD
