name: Superset Frontend

# Only run frontend job on front-end code change
on:
  push:
    branches: [ master ]
    paths:
    - superset-frontend/src/**/*
    - superset-frontend/spec/**/*
  pull_request:
    paths:
    - superset-frontend/package-lock.json

jobs:
  frontend-build:
    name: build
    runs-on: ubuntu-latest
    env:
      CI: github-actions
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache npm
      uses: actions/cache@v1
      with:
        path: |
          ~/.npm
          superset-frontend/.terser-plugin-cache/
        key: ${{ runner.os }}-npm-${{ hashFiles('superset-frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      working-directory: ./superset-frontend
      run: |
        echo "npm: $(npm --version)"
        echo "node: $(node --version)"
        npm ci
    - name: eslint
      working-directory: ./superset-frontend
      run: |
        npm run lint
    - name: unit test
      working-directory: ./superset-frontend
      run: |
        npm run test -- --coverage
    - name: Upload code coverage
      working-directory: ./superset-frontend
      run: |
        bash <(curl -s https://codecov.io/bash)
